const express = require("express")
const userRouter = require("./routes/user.route")
const postRouter = require("./routes/post.route")
const cookieParser = require("cookie-parser")
const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(cookieParser())
app.set('veiw engien','ejs')
app.use("users", userRouter)
app.use("posts", postRouter)
module.exports = app